### PR TITLE
Patternfile Support

### LINKED ISSUE #146: Patternfile Support: Adapter Operation Registration in Meshery Server
**Current Behavior**
Adapter operations are retrieved from Meshery Server using the meshops proto.

**Desired Behavior**
- Implementation of trait definition and workload definitions
- Registration of OAM traits with Meshery Server.

---
**Resources**
See the Meshery and Service Mesh Patterns design spec and the Meshery Architecture deck.

### PR DESCRIPTION
**Pull request by Revolyssup**
**Description**

This PR fixes #146 

Static registration to be added 
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
heads-up - https://github.com/meshery/meshery-consul/pull/193/checks?check_run_id=3547790466

**Comment by Revolyssup** [comment]
> heads-up - https://github.com/meshery/meshery-consul/pull/193/checks?check_run_id=3547790466

yups fixing it

**Comment by Revolyssup** [comment]
@leecalcote  the linting issue is due to the fact that I am using a variable in http.Get. But as I got to know right now(more like reminded),that a function for exactly this thing exists in meshery/models/walker which is to be moved to meshkit along with few other functions.

So I am keeping this PR at hold, as soon as meshkit gets those functions with a new release. So the function causing the linting issue is going to get removed anyways.

**Review by leecalcote — APPROVED** [review]
Pattern support is urgently needed for ServiceMeshCon recording.

**Comment by Revolyssup** [comment]
> Notes from Utkarsh, "merging under the understanding that runtime generation is not likely to be working in this PR, however, this PR does contain prebuilt components that can be used for immediate demo."

@utkarsh-pro  as soon as you put the gitwalker into meshkit, I can use that here and runtime component generation will start working.

**Pull request merged**
