### PR TITLE
Remove bats tests

### LINKED ISSUE #236: [CI] Displace BATS tests
At this point, we have abandoned the BATS test in favor of the new style integration tests. It's time to remove / replace those BATS tests.

_Originally posted by @leecalcote in https://github.com/meshery/meshery-consul/issues/235#issuecomment-1020489954_

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #236 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
the lint workflow refers to old actions versions and outdated Golang version.

**Comment by Revolyssup** [comment]
> the lint workflow refers to old actions versions and outdated Golang version.

Done

**Comment by Revolyssup** [comment]
@leecalcote  The failing test is due to an older go version on ci.yaml which is effectively being removed in this PR itself. So its safe to merge this

**Comment by leecalcote** [comment]
Thanks for this note about the failures. Makes sense. 

Regarding the new lint workflow, this is non-standard in terms of what the other adapters have, correct? Are you proposing this as a universal change? If not, why the one-off?

**Comment by Revolyssup** [comment]
> Thanks for this note about the failures. Makes sense.
> 
> Regarding the new lint workflow, this is non-standard in terms of what the other adapters have, correct? Are you proposing this as a universal change? If not, why the one-off?

This will be replaced by ci.yaml like the ones in other adapters. I will assign that to someone after we merge this.,

**Pull request merged**
