### PR TITLE
Updated the permissions for the user "appuser"

### LINKED ISSUE #274: Permission issue in container
#### Current Behavior

`mkdir /home/appuser/templates/oam/workloads/v0.44.0: permission denied`
#### Expected Behavior

Dockerfile should be improved to avoid such permission issue
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Yh010**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=GuORhAA)
Signed-off-by: Yash Hegde<yash4success@gmail.com>

**Description**

This PR fixes #274 

-  Yes, I signed my commits.

### CODE REVIEW

**Comment by Revolyssup** [comment]
@Yh010 The build is failing. https://github.com/meshery/meshery-consul/actions/runs/4048145374/jobs/6997395930#step:4:107

**Comment by Revolyssup** [comment]
I dont think we should be running container as root.

**Comment by Yh010** [comment]
@Revolyssup yup i forgot to change line number 10..modified the PR now, pls review it.

**Comment by Revolyssup** [comment]
> @Revolyssup yup i forgot to change line number 10..modified the PR now, pls review it.

I think you added some binary instead of removing root user

**Comment by Revolyssup** [comment]
I think this is fixed here https://github.com/meshery/meshery-consul/pull/358

**Pull request closed without merging**
